"""rename parser_class to parser_name

Revision ID: 39c80f3684ae
Revises: ab8a7a962bc2
Create Date: 2026-07-08 16:32:02.046284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c80f3684ae'
down_revision: Union[str, Sequence[str], None] = 'ab8a7a962bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "sources",
        sa.Column(
            "parser_name",
            sa.String(length=100),
            nullable=False,
            server_default="kmu",
        ),
    )

    op.add_column(
        "sources",
        sa.Column(
            "priority",
            sa.Integer(),
            nullable=False,
            server_default="100",
        ),
    )

    op.add_column(
        "sources",
        sa.Column(
            "check_interval",
            sa.Integer(),
            nullable=False,
            server_default="3600",
        ),
    )

    op.add_column(
        "sources",
        sa.Column(
            "last_check",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        "sources",
        sa.Column(
            "last_success",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        "sources",
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False,
            server_default="idle",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'status')
    op.drop_column('sources', 'last_success')
    op.drop_column('sources', 'last_check')
    op.drop_column('sources', 'check_interval')
    op.drop_column('sources', 'priority')
    op.drop_column('sources', 'parser_name')
    # ### end Alembic commands ###
